# Generated by Django 4.2.14 on 2024-07-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hive',
            name='humidity_threshold_high',
        ),
        migrations.RemoveField(
            model_name='hive',
            name='humidity_threshold_low',
        ),
        migrations.RemoveField(
            model_name='hive',
            name='sound_threshold_high',
        ),
        migrations.RemoveField(
            model_name='hive',
            name='temperature_threshold_high',
        ),
        migrations.RemoveField(
            model_name='hive',
            name='temperature_threshold_low',
        ),
        migrations.AddField(
            model_name='hive',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hive',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hive',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hive',
            name='apiary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='accounts.apiary'),
        ),
    ]
